### ISSUE TITLE
Prepare tutorial materials for EDM activity (November 16)

### ISSUE THREAD

**Issue by ha0ye** [weecology/forecasting-dynamics-course#12]
assigning to myself (@ha0ye)

EDIT: (rather, someone with write privileges should assign to me)

**Comment by ethanwhite** [comment]
Done last fall. Thanks @ha0ye! Are you interested in teaching this again this year?

**Comment by ha0ye** [comment]
Sure, assuming scheduling works out. I think I might be gone November 8-15.
