### ISSUE TITLE
Swap out Hobbs paper for one of Treddenick's recent papers

### ISSUE THREAD

**Issue by ethanwhite** [weecology/forecasting-dynamics-course#13]
Hobbs paper is very long and detailed. Students likely don't finish reading it.

Treddenick's recent papers:

* http://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=3451&context=wild_facpub
* http://onlinelibrary.wiley.com/doi/10.1002/ecs2.1525/full

**Comment by skmorgane** [comment]
done!
